name: PHP CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.3'
                extensios: mbstring, xml
                tools: composer

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress

            - name: Run tests
              run: ./vendor/bin/phpunit